<h3>Adicionar Usuario</h3>
  <form method="post">
      Informe o nome do usuario..: 
      <br>
      <input type="text" name="nome">
      <br><br>
      Informe o cpf do usuario..: 
      <br>
      <input type="text" name="cpf">
      <br><br>
      Informe a idade do usuario..: 
      <br>
      <input type="text" name="idade">
      <br><br>
      Informe o sexo do usuario..: 
      <br>
      <input type="text" name="sexo">
      <br><br>
      <input type="submit" value="Adicionar">
  </form>
  <br><br>
  <?php echo $this->resp; ?>