<h3>Quantas vacinas o paciente tomou</h3>
<form method="post">
	Usuario..: <select name="id-usuario">
       <?php foreach ($this->usuarios as $u): ?>
      <option value="<?php echo $u->usuarioId; ?>">
          <?php echo $u->nome; ?>
      </option>
      <?php endforeach; ?>
      </select> <br>
	<br> <input type="submit" value="Ver">
</form>
<br>
<?php
if(isset($this->qtvacinas)){
	echo "<strong>O paciente tomou " . $this->qtvacinas . " vacina(s)</strong>";
}
	
?>
<br>
<br>
<?php echo $this->resp; ?>