<div class="jumbotron">
	<h1><?php echo sprintf($this->translate('Controle de Vacinas %sOnline%s'), '<span class="zf-green">', '</span>') ?><img
			src="/img/vacicon.png" style="width: 100px">
	</h1>
	<p>Sistema para controle de vacinacao online</p>
	<br>
	<p>
		<a class="btn btn-success btn-lg"
			href="<?php
			
			echo $this->url ( 'application/default', array (
					'controller' => 'index',
					'action' => 'cadastrarUsuario' 
			) );
			?>">Cadastrar Usuario</a>
	</p>
	<p>
		<a class="btn btn-success btn-lg"
			href="<?php
			
			echo $this->url ( 'application/default', array (
					'controller' => 'index',
					'action' => 'cadastrarDoenca' 
			) );
			?>">Cadastrar Doenca</a>
	</p>
	<p>
		<a class="btn btn-success btn-lg"
			href="<?php
			
			echo $this->url ( 'application/default', array (
					'controller' => 'index',
					'action' => 'cadastrarVacina' 
			) );
			?>">Cadastrar Vacina</a>
	</p>
	<p>
		<a class="btn btn-success btn-lg"
			href="<?php
			
			echo $this->url ( 'application/default', array (
					'controller' => 'index',
					'action' => 'cadastrarTipoVacina' 
			) );
			?>">Cadastrar Tipos de Vacina</a>
	</p>
	<p>
		<a class="btn btn-success btn-lg"
			href="<?php
			
			echo $this->url ( 'application/default', array (
					'controller' => 'index',
					'action' => 'associarVacina' 
			) );
			?>">Associar Vacina ao Paciente</a>
	</p>

</div>
<p>
	<a
		href="<?php
		
		echo $this->url ( 'application/default', array (
				'controller' => 'index',
				'action' => 'criterio1' 
		) );
		?>">Quais vacinas o paciente tomou</a> <br><a
		href="<?php
		
		echo $this->url ( 'application/default', array (
				'controller' => 'index',
				'action' => 'criterio2' 
		) );
		?>">Vacinas por intervalo</a> <br>
		<a
		href="<?php
		
		echo $this->url ( 'application/default', array (
				'controller' => 'index',
				'action' => 'criterio2' 
		) );
		?>">Quantas vacina o paciente tomou</a>
</p>
